---
services:
  nautobot:
    command: "nautobot-server runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - "../config/nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../jobs:/opt/nautobot/jobs"
      - "../plugins/plugin_example/nautobot_example_plugin:/usr/local/lib/python3.12/site-packages/nautobot_example_plugin"
      # - "../templates/hostname_check_results.html:/usr/local/lib/python3.12/site-packages/nautobot/extras/templates/extras/inc/hostname_check_results.html"
      # - "../templates/customized_jobresult.html:/usr/local/lib/python3.12/site-packages/nautobot/extras/templates/extras/jobresult.html"
    healthcheck:
      interval: "30s"
      timeout: "10s"
      start_period: "60s"
      retries: 3
      test: ["CMD", "true"]  # Due to layering, disable: true won't work. Instead, change the test
  celery_worker:
    volumes:
      - "../config/nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../jobs:/opt/nautobot/jobs"
      - "../plugins/plugin_example/nautobot_example_plugin:/usr/local/lib/python3.12/site-packages/nautobot_example_plugin"
